# Generated by Django 5.0.14 on 2026-06-09 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150, verbose_name='Customer Name')),
                ('customer_address', models.TextField(blank=True, null=True, verbose_name='Customer Address')),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_given', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Given')),
                ('amount_to_be_given', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount to be Given')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.product')),
            ],
        ),
    ]
