# Generated by Django 5.0.14 on 2026-06-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_product_company_name_product_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
