# Generated by Django 5.0.14 on 2026-06-09 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_order_customer_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='product',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='total',
        ),
        migrations.AddField(
            model_name='bill',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount_given',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Given'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='amount_to_be_given',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount to be Given'),
        ),
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='portal.bill')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.product')),
            ],
        ),
    ]
