# Generated by Django 5.0.14 on 2026-06-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_remove_bill_product_remove_bill_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_entered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
