# Generated by Django 5.0.14 on 2026-06-16 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_remove_sku_and_fix_stock_entered'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entered', models.DateField(verbose_name='Stock Date')),
                ('qty_added', models.IntegerField(verbose_name='Qty Added')),
                ('qty_after', models.IntegerField(verbose_name='Total Qty After Update')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='portal.product')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
    ]
