# Generated by Django 5.0.14 on 2026-06-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_add_customer_phone_to_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone Number'),
        ),
    ]
