# Generated by Django 5.2.8 on 2026-06-16 17:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0010_fix_phone_maxlength'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company/Vendor Name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Paid')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Notes / Description')),
                ('date_paid', models.DateField(default=django.utils.timezone.localdate, verbose_name='Payment Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_paid', '-created_at'],
            },
        ),
    ]
