# Generated by Django 5.0.14 on 2026-06-21 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount_paid_to_vendor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='remaining_amount_to_vendor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='vendor_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
