# Generated by Django 5.0.14 on 2026-06-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_product_amount_paid_to_vendor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('ONLINE', 'Online / Card')], default='CASH', max_length=10),
        ),
    ]
