# Generated by Django 5.2.8 on 2026-06-22 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_productbatch_batchsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
