# Generated by Django 5.2.8 on 2026-06-22 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_vendorpaymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_vendor_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
