# Generated by Django 5.2.8 on 2026-06-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_product_total_vendor_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorpaymenthistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
