# Generated by Django 5.0.14 on 2026-08-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_vendorpaymenthistory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Phone Number'),
        ),
    ]
